- hosts: all
  pre_tasks:
    - name: Update pacman cache
      become: true
      community.general.pacman:
        update_cache: true
  roles:
    - role: bootstrap
      become: true
    - role: xorg-tasks
      become: true
    - role: desktop-environment
      become: true
    - role: fonts
      become: true
    - role: soundsystem
      become: true
    - role: guiapps
      become: true
    - role: tweaks
      become: true
    - role: aur-packages
      become: true