- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Installing yay
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: yay
    use: makepkg
- name: Install jetbrains-toolbox
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: jetbrains-toolbox
    use: yay
- name: Install volctl
  become: true
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: volctl
    use: yay
- name: Install visual-studio-code-bin
  become: True
  become_user: "aur_builder"
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    use: yay
- name: Delete the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: yes
- name: Remove `aur_builder` from the sudoers group
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    state: absent
    validate: 'visudo -cf %s'
