- name: Installs pipewire
  become: true
  community.general.pacman:
    name: pipewire
    state: present
- name: Installs wireplumber
  become: true
  community.general.pacman:
    name: wireplumber
    state: present
- name: Installs pipewire-pulse
  become: true
  community.general.pacman:
    name: pipewire-pulse
    state: present
- name: Installs pavucontrol
  become: true
  community.general.pacman:
    name: pavucontrol
    state: present
- name: Installs pamixer
  become: true
  community.general.pacman:
    name: pamixer
    state: present
- name: "Enable pipewire service for {{ ansible_user_id }} "
  become: false
  ansible.builtin.systemd:
    name: pipewire
    enabled: true
    scope: user
- name: "Enable pipewire-pulse service for {{ ansible_user_id }} "
  become: false
  ansible.builtin.systemd:
    name: pipewire-pulse
    enabled: true
    scope: user