- name: Installs pipewire
  community.general.pacman:
    name: pipewire
    state: present
- name: Installs wireplumber
  community.general.pacman:
    name: wireplumber
    state: present
- name: Installs pipewire-pulse
  community.general.pacman:
    name: pipewire-pulse
    state: present
- name: Installs pavucontrol
  community.general.pacman:
    name: pavucontrol
    state: present
- name: Installs pamixer
  community.general.pacman:
    name: pamixer
    state: present