- name: Disables mouse acceleration using libinput
  copy:
    dest: "/etc/X11/xorg.conf.d/50-mouse-acceleration.conf"
    content: |
      Section "InputClass"
        Identifier "Logitech catchall"
        Driver "libinput"
        MatchIsPointer "yes"
        Option "AccelProfile" "flat"
        Option "AccelSpeed" "0"
      EndSection
