- name: Disables mouse acceleration
  copy:
    dest: "/etc/X11/xorg.conf.d/50-mouse-acceleration.conf"
    content: |
      Section "InputClass"
        Identifier "Logitech catchall"
        MatchIsPointer "yes"
        Option "AccelerationProfile" "-1"
        Option "AccelerationScheme" "none"
        Option "AccelSpeed" "-1"
      EndSection
